# Generated by Django 4.2.8 on 2023-12-21 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=255)),
                ('number_of_users', models.IntegerField()),
                ('about_platform', models.TextField()),
                ('request_description', models.TextField()),
                ('expected_date', models.DateTimeField()),
                ('anything_else', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Initiation', max_length=25)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('ETH', 'Ethiopia')], max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('tin_number', models.IntegerField()),
                ('business_classification', models.CharField(max_length=255)),
                ('industry', models.TextField(choices=[('IT', 'Information Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('business', 'Business')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
