# Generated by Django 4.2.8 on 2023-12-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerRequest', '0002_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
