# Generated by Django 4.2.8 on 2023-12-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerRequest', '0003_alter_customerrequest_status_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
    ]
