# Generated by Django 4.2.8 on 2023-12-21 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customerRequest', '0004_rename_name_company_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
