# Generated by Django 4.2.8 on 2023-12-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerRequest', '0004_rename_request_schedule_request_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='request_owner',
            new_name='request',
        ),
    ]
