# Generated by Django 4.2.8 on 2023-12-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerRequest', '0005_rename_request_owner_schedule_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='offer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
